#!/usr/bin/env bash

time curl -H "Content-Type: application/json" -XPOST localhost:9000/batch/post/user --data-binary @tmp
time curl -H "Content-Type: application/json" -XGET localhost:9000/count -d '{"filter":[[{"user":{"referrer":["TWITTER"]}}]],"buckets":["user"],"dimensions":["gender"]}' > result
echo >> result
time curl -H "Content-Type: application/json" -XPOST localhost:9000/immutate/user
time curl -H "Content-Type: application/json" -XPOST localhost:9000/immutate/init/user
time curl -H "Content-Type: application/json" -XGET localhost:9000/count/static -d '{"filter":[[{"user":{"referrer":["TWITTER"]}}]],"buckets":["user"],"dimensions":["gender"]}' >> result
echo >> result
time curl -H "Content-Type: application/json" -XGET localhost:9000/count -d '{"filter":[[{"user":{"referrer":["TWITTER"]}}]],"buckets":["user"],"dimensions":["gender"]}' >> result
echo >> result
